"""financial analysis table

Revision ID: 48cb4f53e354
Revises: 421c7df1f5dd
Create Date: 2026-07-20 00:01:09.796020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cb4f53e354'
down_revision: Union[str, Sequence[str], None] = '421c7df1f5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('overall_health_score', sa.Integer(), nullable=True),
    sa.Column('overall_health_status', sa.String(), nullable=True),
    sa.Column('liquidity_health', sa.Integer(), nullable=True),
    sa.Column('profitability_health', sa.Integer(), nullable=True),
    sa.Column('leverage_health', sa.Integer(), nullable=True),
    sa.Column('efficiency_health', sa.Integer(), nullable=True),
    sa.Column('cash_flow_health', sa.Integer(), nullable=True),
    sa.Column('business_stability_health', sa.Integer(), nullable=True),
    sa.Column('growth_health', sa.Integer(), nullable=True),
    sa.Column('risk_flag_count', sa.Integer(), nullable=False),
    sa.Column('highest_severity', sa.String(), nullable=True),
    sa.Column('statement_snapshot', sa.JSON(), nullable=False),
    sa.Column('ratios', sa.JSON(), nullable=False),
    sa.Column('health_scores', sa.JSON(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['enterprise_assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_analyses_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_analyses_fiscal_year'), ['fiscal_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_financial_analyses_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_financial_analyses_assessment_id'))

    op.drop_table('financial_analyses')
    # ### end Alembic commands ###
