"""initial enterprise schema

Revision ID: 504bce8ca058
Revises
Create Date: 2026-07-18 23:02:09.991155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504bce8ca058'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_customers', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Integer(), nullable=True),
    sa.Column('rejected', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.Float(), nullable=True),
    sa.Column('average_credit_score', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_analysis_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('enterprise_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=False),
    sa.Column('years_in_business', sa.Integer(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('business_expansion_stage', sa.String(), nullable=True),
    sa.Column('enterprise_credit_score', sa.Integer(), nullable=False),
    sa.Column('probability_of_default', sa.Float(), nullable=False),
    sa.Column('loss_given_default', sa.Float(), nullable=False),
    sa.Column('expected_loss', sa.Float(), nullable=False),
    sa.Column('risk_rating', sa.String(), nullable=False),
    sa.Column('recommended_loan_amount', sa.Float(), nullable=True),
    sa.Column('recommended_interest_rate', sa.Float(), nullable=True),
    sa.Column('working_capital', sa.Float(), nullable=True),
    sa.Column('loan_recommendation', sa.String(), nullable=False),
    sa.Column('interest_rate_recommendation', sa.String(), nullable=False),
    sa.Column('loan_tenure_recommendation', sa.String(), nullable=False),
    sa.Column('collateral_recommendation', sa.String(), nullable=False),
    sa.Column('liquidity_health', sa.Integer(), nullable=True),
    sa.Column('debt_health', sa.Integer(), nullable=True),
    sa.Column('working_capital_health', sa.Integer(), nullable=True),
    sa.Column('business_stability', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_assessments_id'), ['id'], unique=False)

    op.create_table('fraud_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fraud_detected', sa.Boolean(), nullable=True),
    sa.Column('fraud_risk', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_checks_id'), ['id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('approval', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('ai_analysis', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('fraud_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_checks_id'))

    op.drop_table('fraud_checks')
    with op.batch_alter_table('enterprise_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_assessments_id'))

    op.drop_table('enterprise_assessments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('portfolio_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_analysis_id'))

    op.drop_table('portfolio_analysis')
    # ### end Alembic commands ###
