/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowStudioRouteImport } from './routes/workflow-studio'
import { Route as StressTesting9RouteImport } from './routes/stress-testing-9'
import { Route as StressTestingRouteImport } from './routes/stress-testing'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityDashboardRouteImport } from './routes/security-dashboard'
import { Route as ScenarioPlanningRouteImport } from './routes/scenario-planning'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as RmWorkspaceRouteImport } from './routes/rm-workspace'
import { Route as RiskMonitoringRouteImport } from './routes/risk-monitoring'
import { Route as RiskIntelligenceRouteImport } from './routes/risk-intelligence'
import { Route as RecommendationMarketplaceRouteImport } from './routes/recommendation-marketplace'
import { Route as PromptStudioRouteImport } from './routes/prompt-studio'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as PortfolioOptimizationRouteImport } from './routes/portfolio-optimization'
import { Route as PortfolioIntelligenceRouteImport } from './routes/portfolio-intelligence'
import { Route as PortfolioDashboardRouteImport } from './routes/portfolio-dashboard'
import { Route as PolicyEngineRouteImport } from './routes/policy-engine'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as NlAnalyticsRouteImport } from './routes/nl-analytics'
import { Route as MonitoringDashboardRouteImport } from './routes/monitoring-dashboard'
import { Route as ModelGovernanceRouteImport } from './routes/model-governance'
import { Route as MlTrainingRouteImport } from './routes/ml-training'
import { Route as MlStressRouteImport } from './routes/ml-stress'
import { Route as MlRegistryRouteImport } from './routes/ml-registry'
import { Route as MlPerformanceRouteImport } from './routes/ml-performance'
import { Route as MlInferenceRouteImport } from './routes/ml-inference'
import { Route as MlFeatureImportanceRouteImport } from './routes/ml-feature-importance'
import { Route as MlDriftRouteImport } from './routes/ml-drift'
import { Route as ManagerDashboardRouteImport } from './routes/manager-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmConsoleRouteImport } from './routes/llm-console'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as IntegrationsSyncRouteImport } from './routes/integrations-sync'
import { Route as IntegrationsImportRouteImport } from './routes/integrations-import'
import { Route as IntegrationsConnectorsRouteImport } from './routes/integrations-connectors'
import { Route as GraphAnalyticsRouteImport } from './routes/graph-analytics'
import { Route as FraudRouteImport } from './routes/fraud'
import { Route as FinTwinRouteImport } from './routes/fin-twin'
import { Route as FinTreasuryRouteImport } from './routes/fin-treasury'
import { Route as FinStrategicRouteImport } from './routes/fin-strategic'
import { Route as FinRegulatoryRouteImport } from './routes/fin-regulatory'
import { Route as FinQuantRouteImport } from './routes/fin-quant'
import { Route as FinPortfolioRouteImport } from './routes/fin-portfolio'
import { Route as FinOptimizeRouteImport } from './routes/fin-optimize'
import { Route as FinMarketRouteImport } from './routes/fin-market'
import { Route as FinForecastRouteImport } from './routes/fin-forecast'
import { Route as FinExecutiveRouteImport } from './routes/fin-executive'
import { Route as FinEsgRouteImport } from './routes/fin-esg'
import { Route as FinEconomicRouteImport } from './routes/fin-economic'
import { Route as FinBenchmarkRouteImport } from './routes/fin-benchmark'
import { Route as FinAltdataRouteImport } from './routes/fin-altdata'
import { Route as FeatureImportanceRouteImport } from './routes/feature-importance'
import { Route as FairnessGovernanceRouteImport } from './routes/fairness-governance'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as ExecutiveCenterRouteImport } from './routes/executive-center'
import { Route as EnterpriseSearchRouteImport } from './routes/enterprise-search'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as EntWorkspacesRouteImport } from './routes/ent-workspaces'
import { Route as EntUxRouteImport } from './routes/ent-ux'
import { Route as EntSuccessRouteImport } from './routes/ent-success'
import { Route as EntSecurityRouteImport } from './routes/ent-security'
import { Route as EntOperationsRouteImport } from './routes/ent-operations'
import { Route as EntMonitoringRouteImport } from './routes/ent-monitoring'
import { Route as EntMarketplaceRouteImport } from './routes/ent-marketplace'
import { Route as EntLaunchRouteImport } from './routes/ent-launch'
import { Route as EntIntegrationRouteImport } from './routes/ent-integration'
import { Route as EntDeveloperRouteImport } from './routes/ent-developer'
import { Route as EntDeploymentRouteImport } from './routes/ent-deployment'
import { Route as EntDataRouteImport } from './routes/ent-data'
import { Route as EntBiRouteImport } from './routes/ent-bi'
import { Route as EarlyWarningRouteImport } from './routes/early-warning'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DataFabricRouteImport } from './routes/data-fabric'
import { Route as Customer360RouteImport } from './routes/customer360'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceDashboardRouteImport } from './routes/compliance-dashboard'
import { Route as CommitteeWorkspaceRouteImport } from './routes/committee-workspace'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as CollateralRouteImport } from './routes/collateral'
import { Route as ApiPlatformRouteImport } from './routes/api-platform'
import { Route as AnalystReportRouteImport } from './routes/analyst-report'
import { Route as AnalystDashboardRouteImport } from './routes/analyst-dashboard'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AipWorkflowsRouteImport } from './routes/aip-workflows'
import { Route as AipResearchRouteImport } from './routes/aip-research'
import { Route as AipReportsRouteImport } from './routes/aip-reports'
import { Route as AipRagRouteImport } from './routes/aip-rag'
import { Route as AipPromptsRouteImport } from './routes/aip-prompts'
import { Route as AipMonitoringRouteImport } from './routes/aip-monitoring'
import { Route as AipMemoryRouteImport } from './routes/aip-memory'
import { Route as AipLearningRouteImport } from './routes/aip-learning'
import { Route as AipInvestigationRouteImport } from './routes/aip-investigation'
import { Route as AipGovernanceRouteImport } from './routes/aip-governance'
import { Route as AipExplainabilityRouteImport } from './routes/aip-explainability'
import { Route as AipEvaluationRouteImport } from './routes/aip-evaluation'
import { Route as AipAssistantRouteImport } from './routes/aip-assistant'
import { Route as AipAgentsRouteImport } from './routes/aip-agents'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AccountAggregatorRouteImport } from './routes/account-aggregator'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowStudioRoute = WorkflowStudioRouteImport.update({
  id: '/workflow-studio',
  path: '/workflow-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StressTesting9Route = StressTesting9RouteImport.update({
  id: '/stress-testing-9',
  path: '/stress-testing-9',
  getParentRoute: () => rootRouteImport,
} as any)
const StressTestingRoute = StressTestingRouteImport.update({
  id: '/stress-testing',
  path: '/stress-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityDashboardRoute = SecurityDashboardRouteImport.update({
  id: '/security-dashboard',
  path: '/security-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioPlanningRoute = ScenarioPlanningRouteImport.update({
  id: '/scenario-planning',
  path: '/scenario-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const RmWorkspaceRoute = RmWorkspaceRouteImport.update({
  id: '/rm-workspace',
  path: '/rm-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMonitoringRoute = RiskMonitoringRouteImport.update({
  id: '/risk-monitoring',
  path: '/risk-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIntelligenceRoute = RiskIntelligenceRouteImport.update({
  id: '/risk-intelligence',
  path: '/risk-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationMarketplaceRoute =
  RecommendationMarketplaceRouteImport.update({
    id: '/recommendation-marketplace',
    path: '/recommendation-marketplace',
    getParentRoute: () => rootRouteImport,
  } as any)
const PromptStudioRoute = PromptStudioRouteImport.update({
  id: '/prompt-studio',
  path: '/prompt-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioOptimizationRoute = PortfolioOptimizationRouteImport.update({
  id: '/portfolio-optimization',
  path: '/portfolio-optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIntelligenceRoute = PortfolioIntelligenceRouteImport.update({
  id: '/portfolio-intelligence',
  path: '/portfolio-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioDashboardRoute = PortfolioDashboardRouteImport.update({
  id: '/portfolio-dashboard',
  path: '/portfolio-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyEngineRoute = PolicyEngineRouteImport.update({
  id: '/policy-engine',
  path: '/policy-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const NlAnalyticsRoute = NlAnalyticsRouteImport.update({
  id: '/nl-analytics',
  path: '/nl-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringDashboardRoute = MonitoringDashboardRouteImport.update({
  id: '/monitoring-dashboard',
  path: '/monitoring-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelGovernanceRoute = ModelGovernanceRouteImport.update({
  id: '/model-governance',
  path: '/model-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const MlTrainingRoute = MlTrainingRouteImport.update({
  id: '/ml-training',
  path: '/ml-training',
  getParentRoute: () => rootRouteImport,
} as any)
const MlStressRoute = MlStressRouteImport.update({
  id: '/ml-stress',
  path: '/ml-stress',
  getParentRoute: () => rootRouteImport,
} as any)
const MlRegistryRoute = MlRegistryRouteImport.update({
  id: '/ml-registry',
  path: '/ml-registry',
  getParentRoute: () => rootRouteImport,
} as any)
const MlPerformanceRoute = MlPerformanceRouteImport.update({
  id: '/ml-performance',
  path: '/ml-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MlInferenceRoute = MlInferenceRouteImport.update({
  id: '/ml-inference',
  path: '/ml-inference',
  getParentRoute: () => rootRouteImport,
} as any)
const MlFeatureImportanceRoute = MlFeatureImportanceRouteImport.update({
  id: '/ml-feature-importance',
  path: '/ml-feature-importance',
  getParentRoute: () => rootRouteImport,
} as any)
const MlDriftRoute = MlDriftRouteImport.update({
  id: '/ml-drift',
  path: '/ml-drift',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager-dashboard',
  path: '/manager-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmConsoleRoute = LlmConsoleRouteImport.update({
  id: '/llm-console',
  path: '/llm-console',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSyncRoute = IntegrationsSyncRouteImport.update({
  id: '/integrations-sync',
  path: '/integrations-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsImportRoute = IntegrationsImportRouteImport.update({
  id: '/integrations-import',
  path: '/integrations-import',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsConnectorsRoute = IntegrationsConnectorsRouteImport.update({
  id: '/integrations-connectors',
  path: '/integrations-connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphAnalyticsRoute = GraphAnalyticsRouteImport.update({
  id: '/graph-analytics',
  path: '/graph-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudRoute = FraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const FinTwinRoute = FinTwinRouteImport.update({
  id: '/fin-twin',
  path: '/fin-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const FinTreasuryRoute = FinTreasuryRouteImport.update({
  id: '/fin-treasury',
  path: '/fin-treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const FinStrategicRoute = FinStrategicRouteImport.update({
  id: '/fin-strategic',
  path: '/fin-strategic',
  getParentRoute: () => rootRouteImport,
} as any)
const FinRegulatoryRoute = FinRegulatoryRouteImport.update({
  id: '/fin-regulatory',
  path: '/fin-regulatory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinQuantRoute = FinQuantRouteImport.update({
  id: '/fin-quant',
  path: '/fin-quant',
  getParentRoute: () => rootRouteImport,
} as any)
const FinPortfolioRoute = FinPortfolioRouteImport.update({
  id: '/fin-portfolio',
  path: '/fin-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FinOptimizeRoute = FinOptimizeRouteImport.update({
  id: '/fin-optimize',
  path: '/fin-optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const FinMarketRoute = FinMarketRouteImport.update({
  id: '/fin-market',
  path: '/fin-market',
  getParentRoute: () => rootRouteImport,
} as any)
const FinForecastRoute = FinForecastRouteImport.update({
  id: '/fin-forecast',
  path: '/fin-forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FinExecutiveRoute = FinExecutiveRouteImport.update({
  id: '/fin-executive',
  path: '/fin-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FinEsgRoute = FinEsgRouteImport.update({
  id: '/fin-esg',
  path: '/fin-esg',
  getParentRoute: () => rootRouteImport,
} as any)
const FinEconomicRoute = FinEconomicRouteImport.update({
  id: '/fin-economic',
  path: '/fin-economic',
  getParentRoute: () => rootRouteImport,
} as any)
const FinBenchmarkRoute = FinBenchmarkRouteImport.update({
  id: '/fin-benchmark',
  path: '/fin-benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const FinAltdataRoute = FinAltdataRouteImport.update({
  id: '/fin-altdata',
  path: '/fin-altdata',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureImportanceRoute = FeatureImportanceRouteImport.update({
  id: '/feature-importance',
  path: '/feature-importance',
  getParentRoute: () => rootRouteImport,
} as any)
const FairnessGovernanceRoute = FairnessGovernanceRouteImport.update({
  id: '/fairness-governance',
  path: '/fairness-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveCenterRoute = ExecutiveCenterRouteImport.update({
  id: '/executive-center',
  path: '/executive-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseSearchRoute = EnterpriseSearchRouteImport.update({
  id: '/enterprise-search',
  path: '/enterprise-search',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EntWorkspacesRoute = EntWorkspacesRouteImport.update({
  id: '/ent-workspaces',
  path: '/ent-workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const EntUxRoute = EntUxRouteImport.update({
  id: '/ent-ux',
  path: '/ent-ux',
  getParentRoute: () => rootRouteImport,
} as any)
const EntSuccessRoute = EntSuccessRouteImport.update({
  id: '/ent-success',
  path: '/ent-success',
  getParentRoute: () => rootRouteImport,
} as any)
const EntSecurityRoute = EntSecurityRouteImport.update({
  id: '/ent-security',
  path: '/ent-security',
  getParentRoute: () => rootRouteImport,
} as any)
const EntOperationsRoute = EntOperationsRouteImport.update({
  id: '/ent-operations',
  path: '/ent-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const EntMonitoringRoute = EntMonitoringRouteImport.update({
  id: '/ent-monitoring',
  path: '/ent-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const EntMarketplaceRoute = EntMarketplaceRouteImport.update({
  id: '/ent-marketplace',
  path: '/ent-marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EntLaunchRoute = EntLaunchRouteImport.update({
  id: '/ent-launch',
  path: '/ent-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const EntIntegrationRoute = EntIntegrationRouteImport.update({
  id: '/ent-integration',
  path: '/ent-integration',
  getParentRoute: () => rootRouteImport,
} as any)
const EntDeveloperRoute = EntDeveloperRouteImport.update({
  id: '/ent-developer',
  path: '/ent-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const EntDeploymentRoute = EntDeploymentRouteImport.update({
  id: '/ent-deployment',
  path: '/ent-deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const EntDataRoute = EntDataRouteImport.update({
  id: '/ent-data',
  path: '/ent-data',
  getParentRoute: () => rootRouteImport,
} as any)
const EntBiRoute = EntBiRouteImport.update({
  id: '/ent-bi',
  path: '/ent-bi',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyWarningRoute = EarlyWarningRouteImport.update({
  id: '/early-warning',
  path: '/early-warning',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFabricRoute = DataFabricRouteImport.update({
  id: '/data-fabric',
  path: '/data-fabric',
  getParentRoute: () => rootRouteImport,
} as any)
const Customer360Route = Customer360RouteImport.update({
  id: '/customer360',
  path: '/customer360',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceDashboardRoute = ComplianceDashboardRouteImport.update({
  id: '/compliance-dashboard',
  path: '/compliance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeWorkspaceRoute = CommitteeWorkspaceRouteImport.update({
  id: '/committee-workspace',
  path: '/committee-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const CollateralRoute = CollateralRouteImport.update({
  id: '/collateral',
  path: '/collateral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformRoute = ApiPlatformRouteImport.update({
  id: '/api-platform',
  path: '/api-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystReportRoute = AnalystReportRouteImport.update({
  id: '/analyst-report',
  path: '/analyst-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystDashboardRoute = AnalystDashboardRouteImport.update({
  id: '/analyst-dashboard',
  path: '/analyst-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AipWorkflowsRoute = AipWorkflowsRouteImport.update({
  id: '/aip-workflows',
  path: '/aip-workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AipResearchRoute = AipResearchRouteImport.update({
  id: '/aip-research',
  path: '/aip-research',
  getParentRoute: () => rootRouteImport,
} as any)
const AipReportsRoute = AipReportsRouteImport.update({
  id: '/aip-reports',
  path: '/aip-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AipRagRoute = AipRagRouteImport.update({
  id: '/aip-rag',
  path: '/aip-rag',
  getParentRoute: () => rootRouteImport,
} as any)
const AipPromptsRoute = AipPromptsRouteImport.update({
  id: '/aip-prompts',
  path: '/aip-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const AipMonitoringRoute = AipMonitoringRouteImport.update({
  id: '/aip-monitoring',
  path: '/aip-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AipMemoryRoute = AipMemoryRouteImport.update({
  id: '/aip-memory',
  path: '/aip-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AipLearningRoute = AipLearningRouteImport.update({
  id: '/aip-learning',
  path: '/aip-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AipInvestigationRoute = AipInvestigationRouteImport.update({
  id: '/aip-investigation',
  path: '/aip-investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AipGovernanceRoute = AipGovernanceRouteImport.update({
  id: '/aip-governance',
  path: '/aip-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const AipExplainabilityRoute = AipExplainabilityRouteImport.update({
  id: '/aip-explainability',
  path: '/aip-explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const AipEvaluationRoute = AipEvaluationRouteImport.update({
  id: '/aip-evaluation',
  path: '/aip-evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const AipAssistantRoute = AipAssistantRouteImport.update({
  id: '/aip-assistant',
  path: '/aip-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AipAgentsRoute = AipAgentsRouteImport.update({
  id: '/aip-agents',
  path: '/aip-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAggregatorRoute = AccountAggregatorRouteImport.update({
  id: '/account-aggregator',
  path: '/account-aggregator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-aggregator': typeof AccountAggregatorRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/aip-agents': typeof AipAgentsRoute
  '/aip-assistant': typeof AipAssistantRoute
  '/aip-evaluation': typeof AipEvaluationRoute
  '/aip-explainability': typeof AipExplainabilityRoute
  '/aip-governance': typeof AipGovernanceRoute
  '/aip-investigation': typeof AipInvestigationRoute
  '/aip-learning': typeof AipLearningRoute
  '/aip-memory': typeof AipMemoryRoute
  '/aip-monitoring': typeof AipMonitoringRoute
  '/aip-prompts': typeof AipPromptsRoute
  '/aip-rag': typeof AipRagRoute
  '/aip-reports': typeof AipReportsRoute
  '/aip-research': typeof AipResearchRoute
  '/aip-workflows': typeof AipWorkflowsRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/analyst-dashboard': typeof AnalystDashboardRoute
  '/analyst-report': typeof AnalystReportRoute
  '/api-platform': typeof ApiPlatformRoute
  '/collateral': typeof CollateralRoute
  '/command-center': typeof CommandCenterRoute
  '/committee-workspace': typeof CommitteeWorkspaceRoute
  '/compliance-dashboard': typeof ComplianceDashboardRoute
  '/copilot': typeof CopilotRoute
  '/customer360': typeof Customer360Route
  '/data-fabric': typeof DataFabricRoute
  '/documents': typeof DocumentsRoute
  '/early-warning': typeof EarlyWarningRoute
  '/ent-bi': typeof EntBiRoute
  '/ent-data': typeof EntDataRoute
  '/ent-deployment': typeof EntDeploymentRoute
  '/ent-developer': typeof EntDeveloperRoute
  '/ent-integration': typeof EntIntegrationRoute
  '/ent-launch': typeof EntLaunchRoute
  '/ent-marketplace': typeof EntMarketplaceRoute
  '/ent-monitoring': typeof EntMonitoringRoute
  '/ent-operations': typeof EntOperationsRoute
  '/ent-security': typeof EntSecurityRoute
  '/ent-success': typeof EntSuccessRoute
  '/ent-ux': typeof EntUxRoute
  '/ent-workspaces': typeof EntWorkspacesRoute
  '/enterprise': typeof EnterpriseRoute
  '/enterprise-search': typeof EnterpriseSearchRoute
  '/executive-center': typeof ExecutiveCenterRoute
  '/explainability': typeof ExplainabilityRoute
  '/fairness-governance': typeof FairnessGovernanceRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/fin-altdata': typeof FinAltdataRoute
  '/fin-benchmark': typeof FinBenchmarkRoute
  '/fin-economic': typeof FinEconomicRoute
  '/fin-esg': typeof FinEsgRoute
  '/fin-executive': typeof FinExecutiveRoute
  '/fin-forecast': typeof FinForecastRoute
  '/fin-market': typeof FinMarketRoute
  '/fin-optimize': typeof FinOptimizeRoute
  '/fin-portfolio': typeof FinPortfolioRoute
  '/fin-quant': typeof FinQuantRoute
  '/fin-regulatory': typeof FinRegulatoryRoute
  '/fin-strategic': typeof FinStrategicRoute
  '/fin-treasury': typeof FinTreasuryRoute
  '/fin-twin': typeof FinTwinRoute
  '/fraud': typeof FraudRoute
  '/graph-analytics': typeof GraphAnalyticsRoute
  '/integrations-connectors': typeof IntegrationsConnectorsRoute
  '/integrations-import': typeof IntegrationsImportRoute
  '/integrations-sync': typeof IntegrationsSyncRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/llm-console': typeof LlmConsoleRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/ml-drift': typeof MlDriftRoute
  '/ml-feature-importance': typeof MlFeatureImportanceRoute
  '/ml-inference': typeof MlInferenceRoute
  '/ml-performance': typeof MlPerformanceRoute
  '/ml-registry': typeof MlRegistryRoute
  '/ml-stress': typeof MlStressRoute
  '/ml-training': typeof MlTrainingRoute
  '/model-governance': typeof ModelGovernanceRoute
  '/monitoring-dashboard': typeof MonitoringDashboardRoute
  '/nl-analytics': typeof NlAnalyticsRoute
  '/operations': typeof OperationsRoute
  '/policy-engine': typeof PolicyEngineRoute
  '/portfolio-dashboard': typeof PortfolioDashboardRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/portfolio-optimization': typeof PortfolioOptimizationRoute
  '/predict': typeof PredictRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/recommendation-marketplace': typeof RecommendationMarketplaceRoute
  '/risk-intelligence': typeof RiskIntelligenceRoute
  '/risk-monitoring': typeof RiskMonitoringRoute
  '/rm-workspace': typeof RmWorkspaceRoute
  '/scenario': typeof ScenarioRoute
  '/scenario-planning': typeof ScenarioPlanningRoute
  '/security-dashboard': typeof SecurityDashboardRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/stress-testing': typeof StressTestingRoute
  '/stress-testing-9': typeof StressTesting9Route
  '/workflow-studio': typeof WorkflowStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-aggregator': typeof AccountAggregatorRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/aip-agents': typeof AipAgentsRoute
  '/aip-assistant': typeof AipAssistantRoute
  '/aip-evaluation': typeof AipEvaluationRoute
  '/aip-explainability': typeof AipExplainabilityRoute
  '/aip-governance': typeof AipGovernanceRoute
  '/aip-investigation': typeof AipInvestigationRoute
  '/aip-learning': typeof AipLearningRoute
  '/aip-memory': typeof AipMemoryRoute
  '/aip-monitoring': typeof AipMonitoringRoute
  '/aip-prompts': typeof AipPromptsRoute
  '/aip-rag': typeof AipRagRoute
  '/aip-reports': typeof AipReportsRoute
  '/aip-research': typeof AipResearchRoute
  '/aip-workflows': typeof AipWorkflowsRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/analyst-dashboard': typeof AnalystDashboardRoute
  '/analyst-report': typeof AnalystReportRoute
  '/api-platform': typeof ApiPlatformRoute
  '/collateral': typeof CollateralRoute
  '/command-center': typeof CommandCenterRoute
  '/committee-workspace': typeof CommitteeWorkspaceRoute
  '/compliance-dashboard': typeof ComplianceDashboardRoute
  '/copilot': typeof CopilotRoute
  '/customer360': typeof Customer360Route
  '/data-fabric': typeof DataFabricRoute
  '/documents': typeof DocumentsRoute
  '/early-warning': typeof EarlyWarningRoute
  '/ent-bi': typeof EntBiRoute
  '/ent-data': typeof EntDataRoute
  '/ent-deployment': typeof EntDeploymentRoute
  '/ent-developer': typeof EntDeveloperRoute
  '/ent-integration': typeof EntIntegrationRoute
  '/ent-launch': typeof EntLaunchRoute
  '/ent-marketplace': typeof EntMarketplaceRoute
  '/ent-monitoring': typeof EntMonitoringRoute
  '/ent-operations': typeof EntOperationsRoute
  '/ent-security': typeof EntSecurityRoute
  '/ent-success': typeof EntSuccessRoute
  '/ent-ux': typeof EntUxRoute
  '/ent-workspaces': typeof EntWorkspacesRoute
  '/enterprise': typeof EnterpriseRoute
  '/enterprise-search': typeof EnterpriseSearchRoute
  '/executive-center': typeof ExecutiveCenterRoute
  '/explainability': typeof ExplainabilityRoute
  '/fairness-governance': typeof FairnessGovernanceRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/fin-altdata': typeof FinAltdataRoute
  '/fin-benchmark': typeof FinBenchmarkRoute
  '/fin-economic': typeof FinEconomicRoute
  '/fin-esg': typeof FinEsgRoute
  '/fin-executive': typeof FinExecutiveRoute
  '/fin-forecast': typeof FinForecastRoute
  '/fin-market': typeof FinMarketRoute
  '/fin-optimize': typeof FinOptimizeRoute
  '/fin-portfolio': typeof FinPortfolioRoute
  '/fin-quant': typeof FinQuantRoute
  '/fin-regulatory': typeof FinRegulatoryRoute
  '/fin-strategic': typeof FinStrategicRoute
  '/fin-treasury': typeof FinTreasuryRoute
  '/fin-twin': typeof FinTwinRoute
  '/fraud': typeof FraudRoute
  '/graph-analytics': typeof GraphAnalyticsRoute
  '/integrations-connectors': typeof IntegrationsConnectorsRoute
  '/integrations-import': typeof IntegrationsImportRoute
  '/integrations-sync': typeof IntegrationsSyncRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/llm-console': typeof LlmConsoleRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/ml-drift': typeof MlDriftRoute
  '/ml-feature-importance': typeof MlFeatureImportanceRoute
  '/ml-inference': typeof MlInferenceRoute
  '/ml-performance': typeof MlPerformanceRoute
  '/ml-registry': typeof MlRegistryRoute
  '/ml-stress': typeof MlStressRoute
  '/ml-training': typeof MlTrainingRoute
  '/model-governance': typeof ModelGovernanceRoute
  '/monitoring-dashboard': typeof MonitoringDashboardRoute
  '/nl-analytics': typeof NlAnalyticsRoute
  '/operations': typeof OperationsRoute
  '/policy-engine': typeof PolicyEngineRoute
  '/portfolio-dashboard': typeof PortfolioDashboardRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/portfolio-optimization': typeof PortfolioOptimizationRoute
  '/predict': typeof PredictRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/recommendation-marketplace': typeof RecommendationMarketplaceRoute
  '/risk-intelligence': typeof RiskIntelligenceRoute
  '/risk-monitoring': typeof RiskMonitoringRoute
  '/rm-workspace': typeof RmWorkspaceRoute
  '/scenario': typeof ScenarioRoute
  '/scenario-planning': typeof ScenarioPlanningRoute
  '/security-dashboard': typeof SecurityDashboardRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/stress-testing': typeof StressTestingRoute
  '/stress-testing-9': typeof StressTesting9Route
  '/workflow-studio': typeof WorkflowStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-aggregator': typeof AccountAggregatorRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/aip-agents': typeof AipAgentsRoute
  '/aip-assistant': typeof AipAssistantRoute
  '/aip-evaluation': typeof AipEvaluationRoute
  '/aip-explainability': typeof AipExplainabilityRoute
  '/aip-governance': typeof AipGovernanceRoute
  '/aip-investigation': typeof AipInvestigationRoute
  '/aip-learning': typeof AipLearningRoute
  '/aip-memory': typeof AipMemoryRoute
  '/aip-monitoring': typeof AipMonitoringRoute
  '/aip-prompts': typeof AipPromptsRoute
  '/aip-rag': typeof AipRagRoute
  '/aip-reports': typeof AipReportsRoute
  '/aip-research': typeof AipResearchRoute
  '/aip-workflows': typeof AipWorkflowsRoute
  '/alerts': typeof AlertsRoute
  '/analysis': typeof AnalysisRoute
  '/analyst-dashboard': typeof AnalystDashboardRoute
  '/analyst-report': typeof AnalystReportRoute
  '/api-platform': typeof ApiPlatformRoute
  '/collateral': typeof CollateralRoute
  '/command-center': typeof CommandCenterRoute
  '/committee-workspace': typeof CommitteeWorkspaceRoute
  '/compliance-dashboard': typeof ComplianceDashboardRoute
  '/copilot': typeof CopilotRoute
  '/customer360': typeof Customer360Route
  '/data-fabric': typeof DataFabricRoute
  '/documents': typeof DocumentsRoute
  '/early-warning': typeof EarlyWarningRoute
  '/ent-bi': typeof EntBiRoute
  '/ent-data': typeof EntDataRoute
  '/ent-deployment': typeof EntDeploymentRoute
  '/ent-developer': typeof EntDeveloperRoute
  '/ent-integration': typeof EntIntegrationRoute
  '/ent-launch': typeof EntLaunchRoute
  '/ent-marketplace': typeof EntMarketplaceRoute
  '/ent-monitoring': typeof EntMonitoringRoute
  '/ent-operations': typeof EntOperationsRoute
  '/ent-security': typeof EntSecurityRoute
  '/ent-success': typeof EntSuccessRoute
  '/ent-ux': typeof EntUxRoute
  '/ent-workspaces': typeof EntWorkspacesRoute
  '/enterprise': typeof EnterpriseRoute
  '/enterprise-search': typeof EnterpriseSearchRoute
  '/executive-center': typeof ExecutiveCenterRoute
  '/explainability': typeof ExplainabilityRoute
  '/fairness-governance': typeof FairnessGovernanceRoute
  '/feature-importance': typeof FeatureImportanceRoute
  '/fin-altdata': typeof FinAltdataRoute
  '/fin-benchmark': typeof FinBenchmarkRoute
  '/fin-economic': typeof FinEconomicRoute
  '/fin-esg': typeof FinEsgRoute
  '/fin-executive': typeof FinExecutiveRoute
  '/fin-forecast': typeof FinForecastRoute
  '/fin-market': typeof FinMarketRoute
  '/fin-optimize': typeof FinOptimizeRoute
  '/fin-portfolio': typeof FinPortfolioRoute
  '/fin-quant': typeof FinQuantRoute
  '/fin-regulatory': typeof FinRegulatoryRoute
  '/fin-strategic': typeof FinStrategicRoute
  '/fin-treasury': typeof FinTreasuryRoute
  '/fin-twin': typeof FinTwinRoute
  '/fraud': typeof FraudRoute
  '/graph-analytics': typeof GraphAnalyticsRoute
  '/integrations-connectors': typeof IntegrationsConnectorsRoute
  '/integrations-import': typeof IntegrationsImportRoute
  '/integrations-sync': typeof IntegrationsSyncRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/llm-console': typeof LlmConsoleRoute
  '/login': typeof LoginRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/ml-drift': typeof MlDriftRoute
  '/ml-feature-importance': typeof MlFeatureImportanceRoute
  '/ml-inference': typeof MlInferenceRoute
  '/ml-performance': typeof MlPerformanceRoute
  '/ml-registry': typeof MlRegistryRoute
  '/ml-stress': typeof MlStressRoute
  '/ml-training': typeof MlTrainingRoute
  '/model-governance': typeof ModelGovernanceRoute
  '/monitoring-dashboard': typeof MonitoringDashboardRoute
  '/nl-analytics': typeof NlAnalyticsRoute
  '/operations': typeof OperationsRoute
  '/policy-engine': typeof PolicyEngineRoute
  '/portfolio-dashboard': typeof PortfolioDashboardRoute
  '/portfolio-intelligence': typeof PortfolioIntelligenceRoute
  '/portfolio-optimization': typeof PortfolioOptimizationRoute
  '/predict': typeof PredictRoute
  '/prompt-studio': typeof PromptStudioRoute
  '/recommendation-marketplace': typeof RecommendationMarketplaceRoute
  '/risk-intelligence': typeof RiskIntelligenceRoute
  '/risk-monitoring': typeof RiskMonitoringRoute
  '/rm-workspace': typeof RmWorkspaceRoute
  '/scenario': typeof ScenarioRoute
  '/scenario-planning': typeof ScenarioPlanningRoute
  '/security-dashboard': typeof SecurityDashboardRoute
  '/signup': typeof SignupRoute
  '/simulation': typeof SimulationRoute
  '/stress-testing': typeof StressTestingRoute
  '/stress-testing-9': typeof StressTesting9Route
  '/workflow-studio': typeof WorkflowStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-aggregator'
    | '/admin-dashboard'
    | '/aip-agents'
    | '/aip-assistant'
    | '/aip-evaluation'
    | '/aip-explainability'
    | '/aip-governance'
    | '/aip-investigation'
    | '/aip-learning'
    | '/aip-memory'
    | '/aip-monitoring'
    | '/aip-prompts'
    | '/aip-rag'
    | '/aip-reports'
    | '/aip-research'
    | '/aip-workflows'
    | '/alerts'
    | '/analysis'
    | '/analyst-dashboard'
    | '/analyst-report'
    | '/api-platform'
    | '/collateral'
    | '/command-center'
    | '/committee-workspace'
    | '/compliance-dashboard'
    | '/copilot'
    | '/customer360'
    | '/data-fabric'
    | '/documents'
    | '/early-warning'
    | '/ent-bi'
    | '/ent-data'
    | '/ent-deployment'
    | '/ent-developer'
    | '/ent-integration'
    | '/ent-launch'
    | '/ent-marketplace'
    | '/ent-monitoring'
    | '/ent-operations'
    | '/ent-security'
    | '/ent-success'
    | '/ent-ux'
    | '/ent-workspaces'
    | '/enterprise'
    | '/enterprise-search'
    | '/executive-center'
    | '/explainability'
    | '/fairness-governance'
    | '/feature-importance'
    | '/fin-altdata'
    | '/fin-benchmark'
    | '/fin-economic'
    | '/fin-esg'
    | '/fin-executive'
    | '/fin-forecast'
    | '/fin-market'
    | '/fin-optimize'
    | '/fin-portfolio'
    | '/fin-quant'
    | '/fin-regulatory'
    | '/fin-strategic'
    | '/fin-treasury'
    | '/fin-twin'
    | '/fraud'
    | '/graph-analytics'
    | '/integrations-connectors'
    | '/integrations-import'
    | '/integrations-sync'
    | '/knowledge-graph'
    | '/llm-console'
    | '/login'
    | '/manager-dashboard'
    | '/ml-drift'
    | '/ml-feature-importance'
    | '/ml-inference'
    | '/ml-performance'
    | '/ml-registry'
    | '/ml-stress'
    | '/ml-training'
    | '/model-governance'
    | '/monitoring-dashboard'
    | '/nl-analytics'
    | '/operations'
    | '/policy-engine'
    | '/portfolio-dashboard'
    | '/portfolio-intelligence'
    | '/portfolio-optimization'
    | '/predict'
    | '/prompt-studio'
    | '/recommendation-marketplace'
    | '/risk-intelligence'
    | '/risk-monitoring'
    | '/rm-workspace'
    | '/scenario'
    | '/scenario-planning'
    | '/security-dashboard'
    | '/signup'
    | '/simulation'
    | '/stress-testing'
    | '/stress-testing-9'
    | '/workflow-studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-aggregator'
    | '/admin-dashboard'
    | '/aip-agents'
    | '/aip-assistant'
    | '/aip-evaluation'
    | '/aip-explainability'
    | '/aip-governance'
    | '/aip-investigation'
    | '/aip-learning'
    | '/aip-memory'
    | '/aip-monitoring'
    | '/aip-prompts'
    | '/aip-rag'
    | '/aip-reports'
    | '/aip-research'
    | '/aip-workflows'
    | '/alerts'
    | '/analysis'
    | '/analyst-dashboard'
    | '/analyst-report'
    | '/api-platform'
    | '/collateral'
    | '/command-center'
    | '/committee-workspace'
    | '/compliance-dashboard'
    | '/copilot'
    | '/customer360'
    | '/data-fabric'
    | '/documents'
    | '/early-warning'
    | '/ent-bi'
    | '/ent-data'
    | '/ent-deployment'
    | '/ent-developer'
    | '/ent-integration'
    | '/ent-launch'
    | '/ent-marketplace'
    | '/ent-monitoring'
    | '/ent-operations'
    | '/ent-security'
    | '/ent-success'
    | '/ent-ux'
    | '/ent-workspaces'
    | '/enterprise'
    | '/enterprise-search'
    | '/executive-center'
    | '/explainability'
    | '/fairness-governance'
    | '/feature-importance'
    | '/fin-altdata'
    | '/fin-benchmark'
    | '/fin-economic'
    | '/fin-esg'
    | '/fin-executive'
    | '/fin-forecast'
    | '/fin-market'
    | '/fin-optimize'
    | '/fin-portfolio'
    | '/fin-quant'
    | '/fin-regulatory'
    | '/fin-strategic'
    | '/fin-treasury'
    | '/fin-twin'
    | '/fraud'
    | '/graph-analytics'
    | '/integrations-connectors'
    | '/integrations-import'
    | '/integrations-sync'
    | '/knowledge-graph'
    | '/llm-console'
    | '/login'
    | '/manager-dashboard'
    | '/ml-drift'
    | '/ml-feature-importance'
    | '/ml-inference'
    | '/ml-performance'
    | '/ml-registry'
    | '/ml-stress'
    | '/ml-training'
    | '/model-governance'
    | '/monitoring-dashboard'
    | '/nl-analytics'
    | '/operations'
    | '/policy-engine'
    | '/portfolio-dashboard'
    | '/portfolio-intelligence'
    | '/portfolio-optimization'
    | '/predict'
    | '/prompt-studio'
    | '/recommendation-marketplace'
    | '/risk-intelligence'
    | '/risk-monitoring'
    | '/rm-workspace'
    | '/scenario'
    | '/scenario-planning'
    | '/security-dashboard'
    | '/signup'
    | '/simulation'
    | '/stress-testing'
    | '/stress-testing-9'
    | '/workflow-studio'
  id:
    | '__root__'
    | '/'
    | '/account-aggregator'
    | '/admin-dashboard'
    | '/aip-agents'
    | '/aip-assistant'
    | '/aip-evaluation'
    | '/aip-explainability'
    | '/aip-governance'
    | '/aip-investigation'
    | '/aip-learning'
    | '/aip-memory'
    | '/aip-monitoring'
    | '/aip-prompts'
    | '/aip-rag'
    | '/aip-reports'
    | '/aip-research'
    | '/aip-workflows'
    | '/alerts'
    | '/analysis'
    | '/analyst-dashboard'
    | '/analyst-report'
    | '/api-platform'
    | '/collateral'
    | '/command-center'
    | '/committee-workspace'
    | '/compliance-dashboard'
    | '/copilot'
    | '/customer360'
    | '/data-fabric'
    | '/documents'
    | '/early-warning'
    | '/ent-bi'
    | '/ent-data'
    | '/ent-deployment'
    | '/ent-developer'
    | '/ent-integration'
    | '/ent-launch'
    | '/ent-marketplace'
    | '/ent-monitoring'
    | '/ent-operations'
    | '/ent-security'
    | '/ent-success'
    | '/ent-ux'
    | '/ent-workspaces'
    | '/enterprise'
    | '/enterprise-search'
    | '/executive-center'
    | '/explainability'
    | '/fairness-governance'
    | '/feature-importance'
    | '/fin-altdata'
    | '/fin-benchmark'
    | '/fin-economic'
    | '/fin-esg'
    | '/fin-executive'
    | '/fin-forecast'
    | '/fin-market'
    | '/fin-optimize'
    | '/fin-portfolio'
    | '/fin-quant'
    | '/fin-regulatory'
    | '/fin-strategic'
    | '/fin-treasury'
    | '/fin-twin'
    | '/fraud'
    | '/graph-analytics'
    | '/integrations-connectors'
    | '/integrations-import'
    | '/integrations-sync'
    | '/knowledge-graph'
    | '/llm-console'
    | '/login'
    | '/manager-dashboard'
    | '/ml-drift'
    | '/ml-feature-importance'
    | '/ml-inference'
    | '/ml-performance'
    | '/ml-registry'
    | '/ml-stress'
    | '/ml-training'
    | '/model-governance'
    | '/monitoring-dashboard'
    | '/nl-analytics'
    | '/operations'
    | '/policy-engine'
    | '/portfolio-dashboard'
    | '/portfolio-intelligence'
    | '/portfolio-optimization'
    | '/predict'
    | '/prompt-studio'
    | '/recommendation-marketplace'
    | '/risk-intelligence'
    | '/risk-monitoring'
    | '/rm-workspace'
    | '/scenario'
    | '/scenario-planning'
    | '/security-dashboard'
    | '/signup'
    | '/simulation'
    | '/stress-testing'
    | '/stress-testing-9'
    | '/workflow-studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountAggregatorRoute: typeof AccountAggregatorRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AipAgentsRoute: typeof AipAgentsRoute
  AipAssistantRoute: typeof AipAssistantRoute
  AipEvaluationRoute: typeof AipEvaluationRoute
  AipExplainabilityRoute: typeof AipExplainabilityRoute
  AipGovernanceRoute: typeof AipGovernanceRoute
  AipInvestigationRoute: typeof AipInvestigationRoute
  AipLearningRoute: typeof AipLearningRoute
  AipMemoryRoute: typeof AipMemoryRoute
  AipMonitoringRoute: typeof AipMonitoringRoute
  AipPromptsRoute: typeof AipPromptsRoute
  AipRagRoute: typeof AipRagRoute
  AipReportsRoute: typeof AipReportsRoute
  AipResearchRoute: typeof AipResearchRoute
  AipWorkflowsRoute: typeof AipWorkflowsRoute
  AlertsRoute: typeof AlertsRoute
  AnalysisRoute: typeof AnalysisRoute
  AnalystDashboardRoute: typeof AnalystDashboardRoute
  AnalystReportRoute: typeof AnalystReportRoute
  ApiPlatformRoute: typeof ApiPlatformRoute
  CollateralRoute: typeof CollateralRoute
  CommandCenterRoute: typeof CommandCenterRoute
  CommitteeWorkspaceRoute: typeof CommitteeWorkspaceRoute
  ComplianceDashboardRoute: typeof ComplianceDashboardRoute
  CopilotRoute: typeof CopilotRoute
  Customer360Route: typeof Customer360Route
  DataFabricRoute: typeof DataFabricRoute
  DocumentsRoute: typeof DocumentsRoute
  EarlyWarningRoute: typeof EarlyWarningRoute
  EntBiRoute: typeof EntBiRoute
  EntDataRoute: typeof EntDataRoute
  EntDeploymentRoute: typeof EntDeploymentRoute
  EntDeveloperRoute: typeof EntDeveloperRoute
  EntIntegrationRoute: typeof EntIntegrationRoute
  EntLaunchRoute: typeof EntLaunchRoute
  EntMarketplaceRoute: typeof EntMarketplaceRoute
  EntMonitoringRoute: typeof EntMonitoringRoute
  EntOperationsRoute: typeof EntOperationsRoute
  EntSecurityRoute: typeof EntSecurityRoute
  EntSuccessRoute: typeof EntSuccessRoute
  EntUxRoute: typeof EntUxRoute
  EntWorkspacesRoute: typeof EntWorkspacesRoute
  EnterpriseRoute: typeof EnterpriseRoute
  EnterpriseSearchRoute: typeof EnterpriseSearchRoute
  ExecutiveCenterRoute: typeof ExecutiveCenterRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  FairnessGovernanceRoute: typeof FairnessGovernanceRoute
  FeatureImportanceRoute: typeof FeatureImportanceRoute
  FinAltdataRoute: typeof FinAltdataRoute
  FinBenchmarkRoute: typeof FinBenchmarkRoute
  FinEconomicRoute: typeof FinEconomicRoute
  FinEsgRoute: typeof FinEsgRoute
  FinExecutiveRoute: typeof FinExecutiveRoute
  FinForecastRoute: typeof FinForecastRoute
  FinMarketRoute: typeof FinMarketRoute
  FinOptimizeRoute: typeof FinOptimizeRoute
  FinPortfolioRoute: typeof FinPortfolioRoute
  FinQuantRoute: typeof FinQuantRoute
  FinRegulatoryRoute: typeof FinRegulatoryRoute
  FinStrategicRoute: typeof FinStrategicRoute
  FinTreasuryRoute: typeof FinTreasuryRoute
  FinTwinRoute: typeof FinTwinRoute
  FraudRoute: typeof FraudRoute
  GraphAnalyticsRoute: typeof GraphAnalyticsRoute
  IntegrationsConnectorsRoute: typeof IntegrationsConnectorsRoute
  IntegrationsImportRoute: typeof IntegrationsImportRoute
  IntegrationsSyncRoute: typeof IntegrationsSyncRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  LlmConsoleRoute: typeof LlmConsoleRoute
  LoginRoute: typeof LoginRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  MlDriftRoute: typeof MlDriftRoute
  MlFeatureImportanceRoute: typeof MlFeatureImportanceRoute
  MlInferenceRoute: typeof MlInferenceRoute
  MlPerformanceRoute: typeof MlPerformanceRoute
  MlRegistryRoute: typeof MlRegistryRoute
  MlStressRoute: typeof MlStressRoute
  MlTrainingRoute: typeof MlTrainingRoute
  ModelGovernanceRoute: typeof ModelGovernanceRoute
  MonitoringDashboardRoute: typeof MonitoringDashboardRoute
  NlAnalyticsRoute: typeof NlAnalyticsRoute
  OperationsRoute: typeof OperationsRoute
  PolicyEngineRoute: typeof PolicyEngineRoute
  PortfolioDashboardRoute: typeof PortfolioDashboardRoute
  PortfolioIntelligenceRoute: typeof PortfolioIntelligenceRoute
  PortfolioOptimizationRoute: typeof PortfolioOptimizationRoute
  PredictRoute: typeof PredictRoute
  PromptStudioRoute: typeof PromptStudioRoute
  RecommendationMarketplaceRoute: typeof RecommendationMarketplaceRoute
  RiskIntelligenceRoute: typeof RiskIntelligenceRoute
  RiskMonitoringRoute: typeof RiskMonitoringRoute
  RmWorkspaceRoute: typeof RmWorkspaceRoute
  ScenarioRoute: typeof ScenarioRoute
  ScenarioPlanningRoute: typeof ScenarioPlanningRoute
  SecurityDashboardRoute: typeof SecurityDashboardRoute
  SignupRoute: typeof SignupRoute
  SimulationRoute: typeof SimulationRoute
  StressTestingRoute: typeof StressTestingRoute
  StressTesting9Route: typeof StressTesting9Route
  WorkflowStudioRoute: typeof WorkflowStudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-studio': {
      id: '/workflow-studio'
      path: '/workflow-studio'
      fullPath: '/workflow-studio'
      preLoaderRoute: typeof WorkflowStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress-testing-9': {
      id: '/stress-testing-9'
      path: '/stress-testing-9'
      fullPath: '/stress-testing-9'
      preLoaderRoute: typeof StressTesting9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress-testing': {
      id: '/stress-testing'
      path: '/stress-testing'
      fullPath: '/stress-testing'
      preLoaderRoute: typeof StressTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-dashboard': {
      id: '/security-dashboard'
      path: '/security-dashboard'
      fullPath: '/security-dashboard'
      preLoaderRoute: typeof SecurityDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-planning': {
      id: '/scenario-planning'
      path: '/scenario-planning'
      fullPath: '/scenario-planning'
      preLoaderRoute: typeof ScenarioPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rm-workspace': {
      id: '/rm-workspace'
      path: '/rm-workspace'
      fullPath: '/rm-workspace'
      preLoaderRoute: typeof RmWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-monitoring': {
      id: '/risk-monitoring'
      path: '/risk-monitoring'
      fullPath: '/risk-monitoring'
      preLoaderRoute: typeof RiskMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-intelligence': {
      id: '/risk-intelligence'
      path: '/risk-intelligence'
      fullPath: '/risk-intelligence'
      preLoaderRoute: typeof RiskIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendation-marketplace': {
      id: '/recommendation-marketplace'
      path: '/recommendation-marketplace'
      fullPath: '/recommendation-marketplace'
      preLoaderRoute: typeof RecommendationMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-studio': {
      id: '/prompt-studio'
      path: '/prompt-studio'
      fullPath: '/prompt-studio'
      preLoaderRoute: typeof PromptStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-optimization': {
      id: '/portfolio-optimization'
      path: '/portfolio-optimization'
      fullPath: '/portfolio-optimization'
      preLoaderRoute: typeof PortfolioOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-intelligence': {
      id: '/portfolio-intelligence'
      path: '/portfolio-intelligence'
      fullPath: '/portfolio-intelligence'
      preLoaderRoute: typeof PortfolioIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-dashboard': {
      id: '/portfolio-dashboard'
      path: '/portfolio-dashboard'
      fullPath: '/portfolio-dashboard'
      preLoaderRoute: typeof PortfolioDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-engine': {
      id: '/policy-engine'
      path: '/policy-engine'
      fullPath: '/policy-engine'
      preLoaderRoute: typeof PolicyEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nl-analytics': {
      id: '/nl-analytics'
      path: '/nl-analytics'
      fullPath: '/nl-analytics'
      preLoaderRoute: typeof NlAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring-dashboard': {
      id: '/monitoring-dashboard'
      path: '/monitoring-dashboard'
      fullPath: '/monitoring-dashboard'
      preLoaderRoute: typeof MonitoringDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-governance': {
      id: '/model-governance'
      path: '/model-governance'
      fullPath: '/model-governance'
      preLoaderRoute: typeof ModelGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-training': {
      id: '/ml-training'
      path: '/ml-training'
      fullPath: '/ml-training'
      preLoaderRoute: typeof MlTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-stress': {
      id: '/ml-stress'
      path: '/ml-stress'
      fullPath: '/ml-stress'
      preLoaderRoute: typeof MlStressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-registry': {
      id: '/ml-registry'
      path: '/ml-registry'
      fullPath: '/ml-registry'
      preLoaderRoute: typeof MlRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-performance': {
      id: '/ml-performance'
      path: '/ml-performance'
      fullPath: '/ml-performance'
      preLoaderRoute: typeof MlPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-inference': {
      id: '/ml-inference'
      path: '/ml-inference'
      fullPath: '/ml-inference'
      preLoaderRoute: typeof MlInferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-feature-importance': {
      id: '/ml-feature-importance'
      path: '/ml-feature-importance'
      fullPath: '/ml-feature-importance'
      preLoaderRoute: typeof MlFeatureImportanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-drift': {
      id: '/ml-drift'
      path: '/ml-drift'
      fullPath: '/ml-drift'
      preLoaderRoute: typeof MlDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-dashboard': {
      id: '/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-console': {
      id: '/llm-console'
      path: '/llm-console'
      fullPath: '/llm-console'
      preLoaderRoute: typeof LlmConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations-sync': {
      id: '/integrations-sync'
      path: '/integrations-sync'
      fullPath: '/integrations-sync'
      preLoaderRoute: typeof IntegrationsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations-import': {
      id: '/integrations-import'
      path: '/integrations-import'
      fullPath: '/integrations-import'
      preLoaderRoute: typeof IntegrationsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations-connectors': {
      id: '/integrations-connectors'
      path: '/integrations-connectors'
      fullPath: '/integrations-connectors'
      preLoaderRoute: typeof IntegrationsConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph-analytics': {
      id: '/graph-analytics'
      path: '/graph-analytics'
      fullPath: '/graph-analytics'
      preLoaderRoute: typeof GraphAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud': {
      id: '/fraud'
      path: '/fraud'
      fullPath: '/fraud'
      preLoaderRoute: typeof FraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-twin': {
      id: '/fin-twin'
      path: '/fin-twin'
      fullPath: '/fin-twin'
      preLoaderRoute: typeof FinTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-treasury': {
      id: '/fin-treasury'
      path: '/fin-treasury'
      fullPath: '/fin-treasury'
      preLoaderRoute: typeof FinTreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-strategic': {
      id: '/fin-strategic'
      path: '/fin-strategic'
      fullPath: '/fin-strategic'
      preLoaderRoute: typeof FinStrategicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-regulatory': {
      id: '/fin-regulatory'
      path: '/fin-regulatory'
      fullPath: '/fin-regulatory'
      preLoaderRoute: typeof FinRegulatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-quant': {
      id: '/fin-quant'
      path: '/fin-quant'
      fullPath: '/fin-quant'
      preLoaderRoute: typeof FinQuantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-portfolio': {
      id: '/fin-portfolio'
      path: '/fin-portfolio'
      fullPath: '/fin-portfolio'
      preLoaderRoute: typeof FinPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-optimize': {
      id: '/fin-optimize'
      path: '/fin-optimize'
      fullPath: '/fin-optimize'
      preLoaderRoute: typeof FinOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-market': {
      id: '/fin-market'
      path: '/fin-market'
      fullPath: '/fin-market'
      preLoaderRoute: typeof FinMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-forecast': {
      id: '/fin-forecast'
      path: '/fin-forecast'
      fullPath: '/fin-forecast'
      preLoaderRoute: typeof FinForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-executive': {
      id: '/fin-executive'
      path: '/fin-executive'
      fullPath: '/fin-executive'
      preLoaderRoute: typeof FinExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-esg': {
      id: '/fin-esg'
      path: '/fin-esg'
      fullPath: '/fin-esg'
      preLoaderRoute: typeof FinEsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-economic': {
      id: '/fin-economic'
      path: '/fin-economic'
      fullPath: '/fin-economic'
      preLoaderRoute: typeof FinEconomicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-benchmark': {
      id: '/fin-benchmark'
      path: '/fin-benchmark'
      fullPath: '/fin-benchmark'
      preLoaderRoute: typeof FinBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-altdata': {
      id: '/fin-altdata'
      path: '/fin-altdata'
      fullPath: '/fin-altdata'
      preLoaderRoute: typeof FinAltdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-importance': {
      id: '/feature-importance'
      path: '/feature-importance'
      fullPath: '/feature-importance'
      preLoaderRoute: typeof FeatureImportanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fairness-governance': {
      id: '/fairness-governance'
      path: '/fairness-governance'
      fullPath: '/fairness-governance'
      preLoaderRoute: typeof FairnessGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-center': {
      id: '/executive-center'
      path: '/executive-center'
      fullPath: '/executive-center'
      preLoaderRoute: typeof ExecutiveCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-search': {
      id: '/enterprise-search'
      path: '/enterprise-search'
      fullPath: '/enterprise-search'
      preLoaderRoute: typeof EnterpriseSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-workspaces': {
      id: '/ent-workspaces'
      path: '/ent-workspaces'
      fullPath: '/ent-workspaces'
      preLoaderRoute: typeof EntWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-ux': {
      id: '/ent-ux'
      path: '/ent-ux'
      fullPath: '/ent-ux'
      preLoaderRoute: typeof EntUxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-success': {
      id: '/ent-success'
      path: '/ent-success'
      fullPath: '/ent-success'
      preLoaderRoute: typeof EntSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-security': {
      id: '/ent-security'
      path: '/ent-security'
      fullPath: '/ent-security'
      preLoaderRoute: typeof EntSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-operations': {
      id: '/ent-operations'
      path: '/ent-operations'
      fullPath: '/ent-operations'
      preLoaderRoute: typeof EntOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-monitoring': {
      id: '/ent-monitoring'
      path: '/ent-monitoring'
      fullPath: '/ent-monitoring'
      preLoaderRoute: typeof EntMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-marketplace': {
      id: '/ent-marketplace'
      path: '/ent-marketplace'
      fullPath: '/ent-marketplace'
      preLoaderRoute: typeof EntMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-launch': {
      id: '/ent-launch'
      path: '/ent-launch'
      fullPath: '/ent-launch'
      preLoaderRoute: typeof EntLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-integration': {
      id: '/ent-integration'
      path: '/ent-integration'
      fullPath: '/ent-integration'
      preLoaderRoute: typeof EntIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-developer': {
      id: '/ent-developer'
      path: '/ent-developer'
      fullPath: '/ent-developer'
      preLoaderRoute: typeof EntDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-deployment': {
      id: '/ent-deployment'
      path: '/ent-deployment'
      fullPath: '/ent-deployment'
      preLoaderRoute: typeof EntDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-data': {
      id: '/ent-data'
      path: '/ent-data'
      fullPath: '/ent-data'
      preLoaderRoute: typeof EntDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ent-bi': {
      id: '/ent-bi'
      path: '/ent-bi'
      fullPath: '/ent-bi'
      preLoaderRoute: typeof EntBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-warning': {
      id: '/early-warning'
      path: '/early-warning'
      fullPath: '/early-warning'
      preLoaderRoute: typeof EarlyWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-fabric': {
      id: '/data-fabric'
      path: '/data-fabric'
      fullPath: '/data-fabric'
      preLoaderRoute: typeof DataFabricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer360': {
      id: '/customer360'
      path: '/customer360'
      fullPath: '/customer360'
      preLoaderRoute: typeof Customer360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-dashboard': {
      id: '/compliance-dashboard'
      path: '/compliance-dashboard'
      fullPath: '/compliance-dashboard'
      preLoaderRoute: typeof ComplianceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee-workspace': {
      id: '/committee-workspace'
      path: '/committee-workspace'
      fullPath: '/committee-workspace'
      preLoaderRoute: typeof CommitteeWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collateral': {
      id: '/collateral'
      path: '/collateral'
      fullPath: '/collateral'
      preLoaderRoute: typeof CollateralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-platform': {
      id: '/api-platform'
      path: '/api-platform'
      fullPath: '/api-platform'
      preLoaderRoute: typeof ApiPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst-report': {
      id: '/analyst-report'
      path: '/analyst-report'
      fullPath: '/analyst-report'
      preLoaderRoute: typeof AnalystReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst-dashboard': {
      id: '/analyst-dashboard'
      path: '/analyst-dashboard'
      fullPath: '/analyst-dashboard'
      preLoaderRoute: typeof AnalystDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-workflows': {
      id: '/aip-workflows'
      path: '/aip-workflows'
      fullPath: '/aip-workflows'
      preLoaderRoute: typeof AipWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-research': {
      id: '/aip-research'
      path: '/aip-research'
      fullPath: '/aip-research'
      preLoaderRoute: typeof AipResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-reports': {
      id: '/aip-reports'
      path: '/aip-reports'
      fullPath: '/aip-reports'
      preLoaderRoute: typeof AipReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-rag': {
      id: '/aip-rag'
      path: '/aip-rag'
      fullPath: '/aip-rag'
      preLoaderRoute: typeof AipRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-prompts': {
      id: '/aip-prompts'
      path: '/aip-prompts'
      fullPath: '/aip-prompts'
      preLoaderRoute: typeof AipPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-monitoring': {
      id: '/aip-monitoring'
      path: '/aip-monitoring'
      fullPath: '/aip-monitoring'
      preLoaderRoute: typeof AipMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-memory': {
      id: '/aip-memory'
      path: '/aip-memory'
      fullPath: '/aip-memory'
      preLoaderRoute: typeof AipMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-learning': {
      id: '/aip-learning'
      path: '/aip-learning'
      fullPath: '/aip-learning'
      preLoaderRoute: typeof AipLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-investigation': {
      id: '/aip-investigation'
      path: '/aip-investigation'
      fullPath: '/aip-investigation'
      preLoaderRoute: typeof AipInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-governance': {
      id: '/aip-governance'
      path: '/aip-governance'
      fullPath: '/aip-governance'
      preLoaderRoute: typeof AipGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-explainability': {
      id: '/aip-explainability'
      path: '/aip-explainability'
      fullPath: '/aip-explainability'
      preLoaderRoute: typeof AipExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-evaluation': {
      id: '/aip-evaluation'
      path: '/aip-evaluation'
      fullPath: '/aip-evaluation'
      preLoaderRoute: typeof AipEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-assistant': {
      id: '/aip-assistant'
      path: '/aip-assistant'
      fullPath: '/aip-assistant'
      preLoaderRoute: typeof AipAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aip-agents': {
      id: '/aip-agents'
      path: '/aip-agents'
      fullPath: '/aip-agents'
      preLoaderRoute: typeof AipAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-aggregator': {
      id: '/account-aggregator'
      path: '/account-aggregator'
      fullPath: '/account-aggregator'
      preLoaderRoute: typeof AccountAggregatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountAggregatorRoute: AccountAggregatorRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AipAgentsRoute: AipAgentsRoute,
  AipAssistantRoute: AipAssistantRoute,
  AipEvaluationRoute: AipEvaluationRoute,
  AipExplainabilityRoute: AipExplainabilityRoute,
  AipGovernanceRoute: AipGovernanceRoute,
  AipInvestigationRoute: AipInvestigationRoute,
  AipLearningRoute: AipLearningRoute,
  AipMemoryRoute: AipMemoryRoute,
  AipMonitoringRoute: AipMonitoringRoute,
  AipPromptsRoute: AipPromptsRoute,
  AipRagRoute: AipRagRoute,
  AipReportsRoute: AipReportsRoute,
  AipResearchRoute: AipResearchRoute,
  AipWorkflowsRoute: AipWorkflowsRoute,
  AlertsRoute: AlertsRoute,
  AnalysisRoute: AnalysisRoute,
  AnalystDashboardRoute: AnalystDashboardRoute,
  AnalystReportRoute: AnalystReportRoute,
  ApiPlatformRoute: ApiPlatformRoute,
  CollateralRoute: CollateralRoute,
  CommandCenterRoute: CommandCenterRoute,
  CommitteeWorkspaceRoute: CommitteeWorkspaceRoute,
  ComplianceDashboardRoute: ComplianceDashboardRoute,
  CopilotRoute: CopilotRoute,
  Customer360Route: Customer360Route,
  DataFabricRoute: DataFabricRoute,
  DocumentsRoute: DocumentsRoute,
  EarlyWarningRoute: EarlyWarningRoute,
  EntBiRoute: EntBiRoute,
  EntDataRoute: EntDataRoute,
  EntDeploymentRoute: EntDeploymentRoute,
  EntDeveloperRoute: EntDeveloperRoute,
  EntIntegrationRoute: EntIntegrationRoute,
  EntLaunchRoute: EntLaunchRoute,
  EntMarketplaceRoute: EntMarketplaceRoute,
  EntMonitoringRoute: EntMonitoringRoute,
  EntOperationsRoute: EntOperationsRoute,
  EntSecurityRoute: EntSecurityRoute,
  EntSuccessRoute: EntSuccessRoute,
  EntUxRoute: EntUxRoute,
  EntWorkspacesRoute: EntWorkspacesRoute,
  EnterpriseRoute: EnterpriseRoute,
  EnterpriseSearchRoute: EnterpriseSearchRoute,
  ExecutiveCenterRoute: ExecutiveCenterRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  FairnessGovernanceRoute: FairnessGovernanceRoute,
  FeatureImportanceRoute: FeatureImportanceRoute,
  FinAltdataRoute: FinAltdataRoute,
  FinBenchmarkRoute: FinBenchmarkRoute,
  FinEconomicRoute: FinEconomicRoute,
  FinEsgRoute: FinEsgRoute,
  FinExecutiveRoute: FinExecutiveRoute,
  FinForecastRoute: FinForecastRoute,
  FinMarketRoute: FinMarketRoute,
  FinOptimizeRoute: FinOptimizeRoute,
  FinPortfolioRoute: FinPortfolioRoute,
  FinQuantRoute: FinQuantRoute,
  FinRegulatoryRoute: FinRegulatoryRoute,
  FinStrategicRoute: FinStrategicRoute,
  FinTreasuryRoute: FinTreasuryRoute,
  FinTwinRoute: FinTwinRoute,
  FraudRoute: FraudRoute,
  GraphAnalyticsRoute: GraphAnalyticsRoute,
  IntegrationsConnectorsRoute: IntegrationsConnectorsRoute,
  IntegrationsImportRoute: IntegrationsImportRoute,
  IntegrationsSyncRoute: IntegrationsSyncRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  LlmConsoleRoute: LlmConsoleRoute,
  LoginRoute: LoginRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  MlDriftRoute: MlDriftRoute,
  MlFeatureImportanceRoute: MlFeatureImportanceRoute,
  MlInferenceRoute: MlInferenceRoute,
  MlPerformanceRoute: MlPerformanceRoute,
  MlRegistryRoute: MlRegistryRoute,
  MlStressRoute: MlStressRoute,
  MlTrainingRoute: MlTrainingRoute,
  ModelGovernanceRoute: ModelGovernanceRoute,
  MonitoringDashboardRoute: MonitoringDashboardRoute,
  NlAnalyticsRoute: NlAnalyticsRoute,
  OperationsRoute: OperationsRoute,
  PolicyEngineRoute: PolicyEngineRoute,
  PortfolioDashboardRoute: PortfolioDashboardRoute,
  PortfolioIntelligenceRoute: PortfolioIntelligenceRoute,
  PortfolioOptimizationRoute: PortfolioOptimizationRoute,
  PredictRoute: PredictRoute,
  PromptStudioRoute: PromptStudioRoute,
  RecommendationMarketplaceRoute: RecommendationMarketplaceRoute,
  RiskIntelligenceRoute: RiskIntelligenceRoute,
  RiskMonitoringRoute: RiskMonitoringRoute,
  RmWorkspaceRoute: RmWorkspaceRoute,
  ScenarioRoute: ScenarioRoute,
  ScenarioPlanningRoute: ScenarioPlanningRoute,
  SecurityDashboardRoute: SecurityDashboardRoute,
  SignupRoute: SignupRoute,
  SimulationRoute: SimulationRoute,
  StressTestingRoute: StressTestingRoute,
  StressTesting9Route: StressTesting9Route,
  WorkflowStudioRoute: WorkflowStudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
